name = "salesforce-consultants"
compatibility_date = "2024-01-01"

[env.production]
name = "salesforce-consultants-production"
route = "salesforceconsultants.io/*"

[env.staging]
name = "salesforce-consultants-staging"
route = "staging.salesforceconsultants.io/*"

[env.development]
name = "salesforce-consultants-dev"
route = "dev.salesforceconsultants.io/*"

# Build configuration for static site
[build]
command = "echo 'Static site - no build required'" 